<a href="https://colab.research.google.com/github/eridanletalis/linalg/blob/master/linalg_hw_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

**Задания из обеих методичек найдёшь здесь ты.**



Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


Решение. 

Мнемоническое правило, которое помогает лично мне: Если размерности двух матриц написать друг за другом, например, $m \times n$, $n \times k$, то, если "внутренние" размерности совпадают ($n,n$), то перемножение возможно и результирующа матрица будет иметь размерность "внешних" чисел.

1. $AB:(4\times2) (4\times2)$ - невозможно, $BA: (4\times2), (4\times2$) - аналогично
2. $AB:(2\times5) (5\times3$) - возмжно, результат ($2\times3$), $BA:(5\times3) (2\times5$) невозможно.
3. $AB$ возможно, результат $(8\times8)$, $BA$ возможно, результат $(3\times3)$
4. Возможны оба варианта, резульат одинаков $(4\times4)$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



$A + B$ = $\begin{pmatrix}
1 +4 & -2 + (-1)\\ 
3 + 0 & 0 + 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$



$A \times B$ = $\begin{pmatrix}
1*4 + (-2)*0 & 1*(-1) + (-2)*5\\ 
3*4 + 0*0 & 3*(-1) + 0*5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [0]:
A = np.array([[1, -2],[3, 0]])
B = np.array([[4, -1],[0, 5]])
print(f"Исходные матрицы \n{A} и \n{B}")
print(f"Сумма матриц: \n{A+B}")
print(f"Произведение матриц:\n{A@B}")

Исходные матрицы 
[[ 1 -2]
 [ 3  0]] и 
[[ 4 -1]
 [ 0  5]]
Сумма матриц: 
[[ 5 -3]
 [ 3  5]]
Произведение матриц:
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$


Резульататом будет матрица:
$\begin{pmatrix}
3*1- 2 * 0 + 4 * 2 & 3*7 - 2*5 + 4 * (-4)\\ 
3*3 - 2*2 + 4*1 & 3*(-6) -2*(-1) + 4*1
\end{pmatrix}$
=$\begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix}$

In [0]:
A, B, C = np.array([[1,7],[3,-6]]),np.array([[0, 5],[2, -1]]),np.array([[2, -4],[1,1]])
print(f"Исходные матрицы A=\n{A},\n  B=\n{B},\n C=\n{C}")
print(f"Результат равен: \n{3*A - 2*B + 4*C}")

Исходные матрицы A=
[[ 1  7]
 [ 3 -6]],
  B=
[[ 0  5]
 [ 2 -1]],
 C=
[[ 2 -4]
 [ 1  1]]
Результат равен: 
[[ 11  -5]
 [  9 -12]]


    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


$A^{T} = \begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}$ размерностью $(2\times3)$

Исходная матрица имеет размерность $(3\times2)$. Операция $AA^{T}$ будет иметь резульата с размерностью $(3\times3)$, 

операция $A^{T}A$ - $(2\times2)$

$AA^{T} = \begin{pmatrix}
4*4 + 1*1 & 4*5+1*(-2) & 4*2 + 3*1\\
5*4 + (-2) * 1 & 5*5 + 2*2 & 5*2 + (-2) * 3\\
2*4 + 3*1 & 5*2 + (-2)*3 & 2*2 + 3*3
\end{pmatrix} = 
\begin{pmatrix}
17&18&11\\
18&29&4\\
11&4&13
\end{pmatrix}$

$A^{T}A = \begin{pmatrix}
4*4+5*5+2*2&1*4-5*2+3*2&\\
1*4 -5*2 + 2*3&1*1+2*2+3*3
\end{pmatrix} = 
\begin{pmatrix}
45&0\\
0&14\\
\end{pmatrix}$


In [0]:
A = np.array([[4,1], [5,-2], [2,3]])
print(f"Умножение А на А.Т \n{A@A.T}")
print(f"Умножение А.T на A \n{A.T@A}")

Умножение А на А.Т 
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Умножение А.T на A 
[[45  0]
 [ 0 14]]



__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [0]:
def m_dot(A, B):
    s = 0.0     
    tmp = []    
    res = [] 
    if len(B) != len(A[0]): 
        print("Не совпадают размерности")        
    else:
        cnt_row_A = len(A) #cnt_row_A
        cnt_col_A = len(A[0]) #cnt_col_A, cnt_row_B  
        cnt_col_B = len(B[0])  # cnt_col_B
        for z in range(cnt_row_A):
            for j in range(cnt_col_B):
                for i in range(cnt_col_A):
                   s = s + A[z][i] * B[i][j]
                tmp.append(s)
                s = 0.0
            res.append(tmp)
            tmp = []           
    return res

In [0]:
m_dot(A, A.T)

[[17.0, 18.0, 11.0], [18.0, 29.0, 4.0], [11.0, 4.0, 13.0]]

In [0]:
m_dot(A.T, A)

[[45.0, 0.0], [0.0, 14.0]]

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin(x)^2 + cos(x)^2 = 1;$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4*5*9 = 180;$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1*5*9 + 4*8*3+2*6*7-7*5*3-4*2*9 - 8*6*1 = 0.$$



In [0]:
from numpy.linalg import det, matrix_rank, inv
det(np.array([[np.sin(1), -np.cos(1)],[np.cos(1), np.sin(1)]]))

1.0

In [0]:
det(np.array([[4,2,3],[0,5,1],[0,0,9]]))

180.0

In [0]:
det(np.array([[1,2,3],[4,5,6],[7,8,9]]))

0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})=16 $ (Свойство 9, матрица должна быть квадратной);
    
   б) $det(A^{T})=4 $ (Свойство 1);
    
   в) $det(2A)=2^{(количество строк матрицы)}* 4$ (по свойству 2 + нужно учитывать, что каждая строка матрицы буте умножена на 2).   


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



Доказательство.

Видно, что две строки матрицы будут равны между собой, если строку 1 домножить на -2. Следовательно, в матрице существуют линейно зависимые строки и её определитель (по свойству 6) равен нулю. Матрица с нулевым определителем называется вырожденной.


$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = \begin{pmatrix}
-2 & 7 & -3\\ 
4 + (-2*2) & -14+(7*2) & 6 + (-3*2)\\ 
-3 & 7 & 13
\end{pmatrix} = 
\begin{pmatrix}
-2 & 7 & -3\\ 
-3 & 7 & 13 \\
0 & 0 & 0
\end{pmatrix}$$

In [61]:
a = np.array([[-2,7,-3],
             [4,-14,6],
             [-3,7,13]])
det(a)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$


Будем выполнять операции, не менаяющие ранга матрицы.


   а) Вычтем из третьго столбца сначала первый, затем второй. 
   
$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2-1-1 & 3-2-1 & 4-3-1
\end{pmatrix}=\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
0 & 0 & 0
\end{pmatrix};$$ Нулевую строку можно вычеркнуть. Осталось две линейно независимые строки, ранг равен 2



 б) Из третьей строки вычтем первую и вторую, нулевую вычеркнем. 

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 -2 -2& 3-1-2\\ 
2 & 3 & 5 & 6
\end{pmatrix}=
\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix};$$
Осталось три линейно независимые строки, ранг равен 3

In [62]:
a = np.array([[1, 2, 3],
              [1, 1, 1],
              [2, 3, 4]])
matrix_rank(a)

2

In [63]:
b = np.array([[0, 0, 2, 1],
              [0, 0, 2, 2],
              [0, 0, 4, 3],
              [2, 3, 5, 6]])
matrix_rank(b)

3